include: package:very_good_analysis/analysis_options.9.0.0.yaml

linter:
  rules:
    always_use_package_imports: true        # disallows *any* relative import in lib/
    avoid_relative_lib_imports: true        # disallows relative imports in lib/
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    literal_only_boolean_expressions: false
    require_trailing_commas: false
    comment_references: false
    only_throw_errors: false
    avoid_positional_boolean_parameters: false
    use_build_context_synchronously: false
    always_put_required_named_parameters_first: false
    use_late_for_private_fields_and_variables: false
    flutter_style_todos: false
    one_member_abstracts: false
    omit_local_variable_types: false
    avoid_catches_without_on_clauses: false
    avoid_setters_without_getters: false
    avoid_redundant_argument_values: false
    document_ignores: false

analyzer:
  plugins:
    - custom_lint
  errors:
    always_use_package_imports: error   # fail the build on violations
    avoid_relative_lib_imports: error   # optional – blocks “../lib/foo.dart”

custom_lint:
  rules:
#     - missing_provider_scope: false
    # Explicitly disable one lint rule
